/* Generated By:JavaCC: Do not edit this line. ProyectoParserConstants.java */
package parserjj;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProyectoParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int BAR = 6;
  /** RegularExpression Id. */
  int SEMICOLON = 7;
  /** RegularExpression Id. */
  int EQ = 8;
  /** RegularExpression Id. */
  int NOTERMINAL = 9;
  /** RegularExpression Id. */
  int TERMINAL = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<MULTI_LINE_COMMENT>",
    "\"|\"",
    "\";\"",
    "\"::=\"",
    "<NOTERMINAL>",
    "<TERMINAL>",
  };

}
